server:
  port: ${PORT:8080}

logging:
  level:
    org.atmosphere: warn

spring:
  mustache:
    check-template-location: false
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  jpa.defer-datasource-initialization: true

# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin, org.vaadin, dev.hilla, com.tvmsoftware.application

api:
  url: http://localhost:8000